/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsDate, IsOptional, ValidateNested, IsString } from "class-validator";
import { Type } from "class-transformer";
import { DayOffUpdateManyWithoutEmployeesInput } from "./DayOffUpdateManyWithoutEmployeesInput";
import { MeetingUpdateManyWithoutEmployeesInput } from "./MeetingUpdateManyWithoutEmployeesInput";
import { SickLeaveUpdateManyWithoutEmployeesInput } from "./SickLeaveUpdateManyWithoutEmployeesInput";

@InputType()
class EmployeeUpdateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateJoined?: Date | null;

  @ApiProperty({
    required: false,
    type: () => DayOffUpdateManyWithoutEmployeesInput,
  })
  @ValidateNested()
  @Type(() => DayOffUpdateManyWithoutEmployeesInput)
  @IsOptional()
  @Field(() => DayOffUpdateManyWithoutEmployeesInput, {
    nullable: true,
  })
  dayOffs?: DayOffUpdateManyWithoutEmployeesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => MeetingUpdateManyWithoutEmployeesInput,
  })
  @ValidateNested()
  @Type(() => MeetingUpdateManyWithoutEmployeesInput)
  @IsOptional()
  @Field(() => MeetingUpdateManyWithoutEmployeesInput, {
    nullable: true,
  })
  meetings?: MeetingUpdateManyWithoutEmployeesInput;

  @ApiProperty({
    required: false,
    type: () => SickLeaveUpdateManyWithoutEmployeesInput,
  })
  @ValidateNested()
  @Type(() => SickLeaveUpdateManyWithoutEmployeesInput)
  @IsOptional()
  @Field(() => SickLeaveUpdateManyWithoutEmployeesInput, {
    nullable: true,
  })
  sickLeaves?: SickLeaveUpdateManyWithoutEmployeesInput;
}

export { EmployeeUpdateInput as EmployeeUpdateInput };
